### ISSUE TITLE
Philips Hue - color_temp

### ISSUE THREAD

**Issue by colonelmattyman** [pnbruckner/homeassistant-config#1]
Dude this is awesome.  Although I came across an issue where if the lights colour had been set by HA's color_temp slider, only the brightness value was saved because when this slider is used the RGB/hs_color values are left empty.   I'm using Philips Hue so it might be different with other lights?

Essentially to fix this, I added the color_temp field to the attributes. 
 
I changed line 13 from
```
LIGHT_ATTRS = [ATTR_BRIGHTNESS, ATTR_HS_COLOR]
```
to
```
ATTR_HS_COLORTEMP = "color_temp"
LIGHT_ATTRS = [ATTR_BRIGHTNESS, ATTR_HS_COLOR, ATTR_HS_COLORTEMP]
```

I've adjusted your script below and have linked it:
[light_store.txt](https://github.com/pnbruckner/homeassistant-config/files/2228157/light_store.txt)

**Comment by pnbruckner** [comment]
Sorry, didn't see this. I didn't get an e-mail from github; I thought I would. Hmm.

Anyway, thanks. And, yes, it seems some light platforms provide different color attributes than hs_color. Some I've even seen provide more than one color attribute - but they don't agree! And I've seen in recent releases that the light component is treating these various color attributes differently. So I'm not sure what the best long term solution is. E.g., if the script saves any and all color attributes that a light entity provides, but those disagree, what happens when the restore operation tries to set them all?

**Comment by pnbruckner** [comment]
After reviewing the light component code again, it seems clear now a light should only have for a "color" attribute either white_value, color_temp, or (as a set) hs_color, rgb_color and xy_color. The last three are just three representations of the same color (all deriving from hs_color.)

However, it's apparently possible for any light platform code to provide more than one of these. It _does_ make sense to have color_temp and hs_color/rgb_color/xy_color, because color_temp can always be converted to the others. The reverse is not true. I.e., most colors that can be represented as rgb, hs or xy _cannot_ be represented as color_temp. (Color temp is just a line on an xy graph.)

Furthermore, it appears at least some light platforms provide color_temp and hs/rgb/xy when they shouldn't - i.e., the color_temp is valid, but the others are bogus.

So, it would seem the best path forward is for this script to save white_value if it's present, or color_temp if it's present by white_value is not, or hs_color if neither white_value nor color_temp are present.

**Comment by pnbruckner** [comment]
Forgot to close this incident when the change was [committed](https://github.com/pnbruckner/homeassistant-config/commit/3acfb7669cab2e0fa26ac6751e6f42b8a9907a18).
