### ISSUE TITLE
life360 in 0.89.0 map is displayed incorrectly

### ISSUE THREAD

**Issue by anrada73** [pnbruckner/homeassistant-config#107]
in Version 0.89.0b map is displayed incorrectly. no Icons
![icon](https://user-images.githubusercontent.com/43232370/53583592-27247a00-3b82-11e9-8b51-41c04b1e9ba0.jpg)

**Comment by pnbruckner** [comment]
I'm not sure how this affects my life360 platform. I just checked HA's zone component and I see no recent changes that would impact how my platform interacts with it. That's not to say that there isn't something - I just don't see it if there is.

Are you using the life360 `add_zones` option? If so, have you tried disabling that and using HA zones that are created either via the HA config or HA integration interface? Do HA created zones appear the same way?

FYI, the life360 platform's `add_zones` feature, by design, does not add an icon or picture to zones it creates. But the name of the zone, I would think, should at least appear on the map. It does for me.

**Comment by expired00** [comment]
Mine appears to be doing the same thing now that I've updated to 0.89.0 stable. I can still see my locations, but my wife and I aren't appearing. long and lat are still correct for both device trackers and everything else appears fine.

Only log that looks like it might be causing it is:

`
Error loading custom_components.life360.device_tracker. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/loader.py", line 166, in _load_file
    module = importlib.import_module(path)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 962, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.life360.device_tracker'; 'custom_components.life360' is not a package`

**Comment by pnbruckner** [comment]
@expired00 

Not sure what to tell you either. Also, what you said is very confusing. First you say "I can still see my locations", but then you say "but my wife and I aren't appearing." So do you see the device_tracker entities or not? And _where_ do you see them, or not -- the map, the States page, ...? You say "long and lat are still correct for both device trackers and everything else appears fine", but then you show an error implying the life360 custom component did not even load. You've got me really confused.

FWIW, I have my custom component working with the latest 0.89 dev checkout, and I see device_tracker entities on the States page, and they show up on the map for everyone that is not in the home zone.

Again, I'm not saying there isn't an issue, but I'm not understanding exactly what you think the problem is, and what your configuration is that is causing it. Please be much more explicit. If there's a problem I want to solve it, but I can't based on what I've heard in this issue so far.
