### ISSUE TITLE
Life360: Add Circle & Place inclusion/exclusion options

### ISSUE THREAD

**Issue by covertbert** [pnbruckner/homeassistant-config#132]
I'm part of a few different circles, each of which have my home location under a different name and only one of which is called "Home". The problem I have is that, as a result of this, the life360 component reports my state as a variety of different things when I'm at home.

Ideally I want to totally ignore what all but one of my circles calls my home location so that it will match what HA calls my home location and therefore allows me to write scripts based on my home state.

What's the best way to achieve this? Unfortunately I can't change the name of my home location in the other circles without causing drama.

**Comment by pnbruckner** [comment]
I think to properly handle this case (and other, similar cases with multiple Circles) I'd have to reorganize things a bit and possibly allow unique settings per Circle, including whether or not to even include the Circle. That will take a bit more thought than I have time for right now. (But, if you don't mind, I'll keep this issue open to remind me.)

For now I might suggest simply removing `places` from `show_as_state` and just rely on HA's `zone.home` to determine if/when you're home. I guess you probably can't use `add_zones` either.

**Comment by covertbert** [comment]
Cheers for your reply and no worries, that makes sense! Sounds like a perfectly reasonable workaround for now though.

**Comment by pnbruckner** [comment]
@covertbert, coming back to this (and especially since I'm submitting this to become a standard component, and hopefully it will see a lot more use), after re-reading what you said, I think maybe the easiest "fix" would be to add an `exclude_places` config variable. This would apply to both `show_as_state: places` as well as `add_zones`. If a Place name matches one of the strings in the `exclude_places` list, then it will be ignored (as if you're not in that Place.) Then just the GPS location (and HA's zones), and possibly driving & moving, will be used to determine the state. And for `add_zones`, no HA zone will be created/updated from it. How does that sound?

**Comment by pnbruckner** [comment]
@covertbert, hmm, or would it be better to have an optional `circles` config variable, such that only Circles whose name matches a string in that list would be processed? Or maybe both?

**Comment by covertbert** [comment]
@pnbruckner In the end I followed your initial suggestion and just had HA ignore all life360 places which works fine for me because, actually, I'd rather control my HA places from HA without any outside interference.

Having said that, the ability to optionally include some circles and the ability to exclude specific places would certainly benefit many people I'd imagine.

**Comment by pnbruckner** [comment]
Ok, thanks for your feedback. I'm going to leave this open to remind me to work on adding Circle and Place inclusion/exclusion options.

**Comment by pnbruckner** [comment]
I've added circle & member include/exclude options to the life360 integration I'm submitting to become a standard integration. I won't bother to add these to the custom integration.
