### ISSUE TITLE
Life360: Create/update HA zones based on Life360 Places

### ISSUE THREAD

**Issue by pnbruckner** [pnbruckner/homeassistant-config#51]
If it's possible to retrieve Place definitions from the Life360 server, then use them to automatically create (or update???) corresponding HA zones. Make this a configurable option. Then remove places from show_as_state, because it would no longer be necessary.

**Comment by pnbruckner** [comment]
Apparently appending 'places' to the end of a circle URL does return Placed defined for that circle! Woo hoo!

**Comment by pnbruckner** [comment]
The question is, when to poll the Life360 server for this information? It would have to be done for each Circle, and should probably handle when a given Place is defined in more than one Circle. I would assume Place definitions don't change very often, so maybe it makes the most sense to do this once at HA startup.

**Comment by davidkmcgowan** [comment]
Maybe just do it on initial connection, plus nightly?  There will be a delay if you add places in Life360, but they would show up next day.  seems like it has to be time based polling...

You could also use the developer tools, select an entity, put in some json, then force an update, so don't do any timing, just on initial pull, then manually people update when they need too

or both

**Comment by cdrom1028** [comment]
Just wondering if the Names associated with the Place Definitions are being populated? I saw the names show up once, but since I have been adding configs to my system I have had to reboot several times and they no longer appear on the HA Map. I just didn't know if this was a part of your implemenation.

**Comment by pnbruckner** [comment]
If you have add_zones and/or zone_interval defined in your life360 config then it should be creating HA Zones that correspond to your Life360 Places. From the example config:
```
    add_zones: true
    zone_interval:
      minutes: 15
```
Also, if you have DEBUG enabled, you should see something like this in your home-assistant.log:
```
2018-12-28 15:17:13 DEBUG (Thread-6) [custom_components.device_tracker.life360] Checking Places
2018-12-28 15:17:13 DEBUG (Thread-6) [custom_components.device_tracker.life360] Adding zones for Places: Home (Son): xx.xxxxx, yy.yyyyy, zz.z; ...
2018-12-28 15:17:13 DEBUG (Thread-6) [custom_components.device_tracker.life360] Will check Places every: 1:00:00
```

**Comment by cdrom1028** [comment]
I do have those three lines in my configuration.yaml and presence is working beautifully. I am seeing the My Places show on the map as expected. However I see no labels for the places defined.  For what its worth this is just a nit-picky issue but its one that keeps bugging me, only because I saw the labels populate the first time.  If I can get this solved and can come up with a way to set default center location and zoom on the map then I have "struck gold!" 

BTW: thanks for the quick response!! Cheers!

**Comment by pnbruckner** [comment]
@cdrom1028, can't explain that. I just looked over my code and I don't see a reason for this. Must be something in the way the map works. In any case, I'm glad it's working for you now!
