### ISSUE TITLE
Composite with Life360 attributes

### ISSUE THREAD

**Issue by Jayphen** [pnbruckner/homeassistant-config#77]
Thanks for these great addons :)

It would be nice to get some more of the detail from the Life360 tracker in to the composite tracker. Namely, the `speed`, `moving`, `wifi_on`, and `entity_picture` attributes.

**Comment by pnbruckner** [comment]
Thanks. I agree, but unfortunately it's not very straightforward. By its nature, the composite takes data from multiple entities, not all of which have some of these attributes. And even when they do, they can be different (e.t., entity_picture.) So, e.g., if it took `moving` from a Life360 entity, but then took updates from another entity for a while (say a Google Maps Location Sharing entity), the `moving` attribute would be very stale and probably misleading if it was kept around. Or it could be set to `unknown`, but then it would be changing very often. `entity_picture` is another one that is even more problematic. Turns out the device_tracker component only uses that value (i.e., writes it into known_devices.yaml) when the entity is first created. So which entity_picture is used would depend on which type of watched entity was first seen.

What I do is to use the composite tracker for most things -- it's the one I shown on the main page, and use in automations -- but then I also show the individual "input" trackers on another page so I can see their details if I want.

**Comment by Jayphen** [comment]
Thanks for the detailed explanation :) I think my main use case for the request would just be so that I can always rely on the composite entity having the data I’m looking for, making it a bit easier to write automations etc. But I can just use the Life360 entity when I need those attributes.

**Comment by PProvost** [comment]
Sorry to reply to a closed issue, but an idea occurred to me as I was looking for the same thing as @Jayphen . Could you do something like an optional config entry called "entity_picture_template" that you can use to express the desired entity_picture used by the composite.

Something like this:

```
  entity_picture_template: "{{ state_attr('device_tracker.life360_me', 'entity_picture') }}"
```

But if you wanted to avoid the template thing, perhaps something like this:

```
  device_tracker:
  - platform: composite
    name: my_composite
    picture_entity: life360_me
    entity_id:
      - device_tracker.life360_me
      - device_tracker.my_iphone

````

But for now I can do the same thing and edit my known_devices.yaml file.
