### ISSUE TITLE
Multiple accounts of life360

### ISSUE THREAD

**Issue by fcastroruiz** [pnbruckner/homeassistant-config#81]
I have multiple accounts for life360 members, i don´t want my family know my gps position.

When I use this configuration, all device_trackers use only one account of life360.

is posible to use multiple accounts?

Thnks and sorry for my english

configuration.yaml

device_tracker:
  - platform: life360
    prefix: fernando
    username: xxx@yahoo.es
    password: !secret life360_fernando_password
    interval_seconds: 10
    add_zones: false
    max_update_wait:
      minutes: 30
  - platform: life360
    prefix: raquel
    username: xxx@gmail.com
    password: !secret life360_raquel_password
    interval_seconds: 10
    add_zones: false
    max_update_wait:
      minutes: 30
  - platform: life360
    prefix: mamen
    username: xxx@yahoo.es
    password: !secret life360_mamen_password
    interval_seconds: 10
    add_zones: false
    max_update_wait:
      minutes: 30
  - platform: life360
    prefix: carmen
    username: xxxx@gmail.com
    password: !secret life360_carmen_password
    interval_seconds: 10
    add_zones: false
    max_update_wait:
      minutes: 30

**Comment by pnbruckner** [comment]
I've never tried this, but I think you should be able to use multiple accounts, but for each one you'll need to specify a unique value for the `filename` parameter. E.g., `filename: life360_fernando.conf`, etc. The account information is used once to obtain a token that is stored in this file, and then at every restart it will use the token from the file (if it exists.) So since you didn't specify unique filenames for each account, what was happening is that they all used the same token (for one of the accounts) from the default life360.conf file.

**Comment by fcastroruiz** [comment]
I try this, and i think work fine. I try it more time and report you if i have any issue. Thanks a lot.

**Comment by fcastroruiz** [comment]
You can close issue, work fine , thanks a lot

**Comment by pnbruckner** [comment]
Glad it's working for you. For future reference, if you create the issue you can also close it yourself.
