### ISSUE TITLE
Life360 avatar does not update in HA when updated in Life360 account

### ISSUE THREAD

**Issue by quantummobile** [pnbruckner/homeassistant-config#93]
Hello,

do you have an idea why Life360 avatar does not update in HA when it is updated in Life360 account?

Thanks in advance.

**Comment by pnbruckner** [comment]
Hi,

Yes, because the device_tracker component-level code only uses the value from the Life360 server the very first time the device is seen in HA. This value is entered in known_devices.yaml as the value for the picture parameter for the corresponding device, and furthermore, it is not updated afterwards, even if the server provides a new URL. That's just the way the device_tracker code works and there really isn't anything I can do about it.

You need to manually edit known_devices.yaml to update this field. The easiest way to get the new value is to open and log into Life360's website, then right-click on the member's avatar and select "Copy image address". Then paste this for the value of the picture parameter for that member's device entry.

**Comment by quantummobile** [comment]
Hi,

Thank you for such a detailed and prompt reply, it really helped.
Would you consider adding check if picture is updated on the Life360 server and if it is - update value in known_devices.yaml?

Many thanks!

**Comment by pnbruckner** [comment]
known_devices.yaml is managed by the component-level code (i.e., `device_tracker/__init__.py`), and is the same for all device tracker platforms. (E.g., the same would happen if you used Google Maps Location Sharing.) It probably would be nice if it noticed when the picture passed into it (from platform-level code like my life360.py) changed and updated things accordingly. But that would be a feature request. You might consider making that request on the official HA github's Issue page.

**Comment by quantummobile** [comment]
I will consider making a request on the official HA github's Issue page.
Thanks!

**Comment by pnbruckner** [comment]
Actually, I just remembered, they don't want feature requests submitted via the Issues page. If you try, you'll see this:

This is for bugs only. Feature and enhancement requests should go in our community forum: https://community.home-assistant.io/c/feature-requests

But maybe you can still use the Issues page and make it sound like a bug. 😉
